resources:
  repositories:
  - repository: wire-ios-shared-resources
    type: github
    name: wireapp/wire-ios-shared-resources

jobs:
- template: azure/build-and-test.yml@wire-ios-shared-resources
